### ISSUE TITLE
Server error upon adding mod in webui

### ISSUE THREAD

**Issue by Maddremor** [joonatoona/OpenMineMods#1]
```
Error: 500 Internal Server Error

Sorry, the requested URL 'http://127.0.0.1:8096/edit/cffa92abb6ba89827915a2b98b991fc0/add/221857' caused an error:

Internal Server Error
```
Problem encountered when trying to add a mod (any mod) to an instance in WebUI. 
[results.json](https://gist.github.com/Maddremor/a13c92e5a7d0de7d04058b43fd6508c5) from tests.py

I'll have to say, this is the most bleeding edge I've ever been on anything not hommade. Keep up the good work.

**Comment by Maddremor** [comment]
Traceback (most recent call last):
  File "D:\Program Files\Python36\lib\site-packages\bottle.py", line 862, in _handle
    return route.call(**args)
  File "D:\Program Files\Python36\lib\site-packages\bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "webui.py", line 91, in addmodd
    instance.install_mod(file, curse)
  File "D:\Program Files (x86)\Minecraft\CustomSoftware\OpenMineMods\MultiMC.py", line 106, in install_mod
    fname = curse.download_file(file.host + file.url, "{}/minecraft/mods".format(self.path))
  File "D:\Program Files (x86)\Minecraft\CustomSoftware\OpenMineMods\CurseAPI.py", line 119, in download_file
    with open(filepath+"/"+fname, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: "D:\\Program Files (x86)\\Minecraft\\CustomSoftware\\MultiMC/instances\\TestOne/minecraft/mods/Pam's HarvestCraft 1.12c.jar"

**Comment by notjuliee** [comment]
Ok, so I minorly broke the test software. That's a seperate issue I'll look into later.

Does the folder `D:\Program Files (x86)\Minecraft\CustomSoftware\MultiMC\instances\TestOne\minecraft\mods` exist?

I don't have a windows box, so you're the first to proprely test it on windows :D

**Comment by Maddremor** [comment]
You're right, it was a new instance, and the mods folder had not been created by MultiMC.

**Comment by notjuliee** [comment]
Ok. Let me add a failsafe for that, creating the mod folder if it doesn't exist.

**Comment by notjuliee** [comment]
Now it will create the mods folder if it doesn't exist.

Keep in mind you do need to install forge manually.
