### ISSUE TITLE
MacOS builds

### ISSUE THREAD

**Issue by notjuliee** [joonatoona/OpenMineMods#13]
Need a MacOS machine with Python 3.5.2 and OpenMineMods running.

* Install `pyinstaller 3.0.2`
* Run `pyinstaller OpenMineMods.spec`
* Zip the `dist` folder that gets created and upload it somewhere

**Comment by SavageCore** [comment]
Could this be done with travis ci? 

https://docs.travis-ci.com/user/deployment/releases/

**Comment by notjuliee** [comment]
Huh, apparently it can. I will look into setting that up. Thanks!

**Comment by SavageCore** [comment]
If I was more comfortable with Python I'd probably send a PR. You can check out one of [my repos](https://github.com/SavageCore/extract-resource-pack) for an example Electron app being built, I love it!

**Comment by notjuliee** [comment]
Hey @SavageCore , I've got a working travis build for Linux, would you mind helping me get OSX builds and deployment too?

I also see you've got Windows builds working and deploying, would you mind helping me out with that too? :)
