### ISSUE TITLE
Crashes on KDE Plasma (Wayland)

### ISSUE THREAD

**Issue by notjuliee** [joonatoona/OpenMineMods#17]
Refuses to start due to missing Wayland libraries?

**Comment by bastisawesome** [comment]
What are the steps to produce this error? It works fine for me and I am using Plasma 5 on all of my devices.

**Comment by notjuliee** [comment]
Are you running plasma on X or plasman on Wayland?

**Comment by bastisawesome** [comment]
Excellent point, I will get a VM booted up and test with Wayland on Arch Linux. Might take a day or two to get setup, though.
