### ISSUE TITLE
"Unable to execute script main"

### ISSUE THREAD

**Issue by whizzball1** [joonatoona/OpenMineMods#18]
I'm using a 64-bit version of Windows 10. The first release worked for me.

I downloaded windows.zip from the release page and extracted the files into a folder in my documents. (My user folder, which is part of the file hierarchy of openminemods.zip, has an underscore, which has caused me problems in the past with the Twitch Launcher.) I bypassed SmartScreen and ran the file, only to get a dialog box saying "Unable to execute script main".

**Comment by notjuliee** [comment]
Ok, I'm gonna get you a debug build real quick so we can see why it's crashing. Hold on a minute.

**Comment by notjuliee** [comment]
Here's a debug build, can you please run the exe in a command window and send the output?

[Windows_DEBUG.zip](https://github.com/joonatoona/OpenMineMods/files/1304387/Windows_DEBUG.zip)

**Comment by notjuliee** [comment]
Oh, actually I already know the problem. 1.1 is not compatible with the 1.0 database format, can you delete `omm.db.*` from your home folder and `meta.db.*` from your MultiMC folder?

**Comment by whizzball1** [comment]
No such files exist.

**Comment by notjuliee** [comment]
OK, so what does the debug binary output?

**Comment by whizzball1** [comment]
"FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/Jonan_Rohi/Documents/games/Minecraft/New MultiMC/meta.db.dat'"
This is most relevant. My MultiMC directory is no longer /games/Minecraft/New MultiMC; it is /Games/Minecraft/MultiMC.

**Comment by notjuliee** [comment]
Oh, that makes sense. So what you're gonna need to do is go into `C:/Users/Jonan_Rohi/`, and delete all 3 files that start with `omm.db`. That should reset your preferences.

Make sure you also delete all 3 files that start with `omm.db` in your MultiMC folder.

**Comment by whizzball1** [comment]
Ah, that's what you meant by home folder. I should be fine if there's no omm.db in MultiMC, right?

**Comment by notjuliee** [comment]
Yes, that's what I meant. I should have made that more clear, sorry.

The file is `meta.db` in the MultiMC folder.

**Comment by whizzball1** [comment]
Got it working!

**Comment by notjuliee** [comment]
Awesome!
