### ISSUE TITLE
List of installed mods empty on startup

### ISSUE THREAD

**Issue by Maddremor** [joonatoona/OpenMineMods#22]
Upon starting OMM, the list of mods in an instance is empty even if here are mods installed in the proper mods dir of said instance. This includes mods installed by OMM. When installing a mod, it is added to the list of installed mods, but the entry only last that session leaving the list empty on the nex restart

I use Windows 10 and has observed this with both the released executable and with manually running main.py from a cloned repo.

**Comment by notjuliee** [comment]
The mods not installed by OMM will never show up, that is intended behavior.

It adds it to the list? That list is pulled from disk, so I have no clue why it wouldn't persist.

Can you try the `ui-v2` branch?

**Comment by Maddremor** [comment]
`ui-v2`, doesn't work for me, but thats a separate issue and possibly my fault. 
Where does OMM store the list in question? Could be a permission problem. I could check if anything is written to it.

**Comment by notjuliee** [comment]
Please open an issue for that too :/

Its stored in meta.db in your MultiMC folder. Its probably not your fault, there's a ton of bugginess going on with persistence, I'm rewriting it for 2.0.

**Comment by notjuliee** [comment]
Actually don't open an issue for ui-v2. The meta format isn't compatible, you need to delete meta.db from your mmc folder.

**Comment by Maddremor** [comment]
I see `meta.db.bak`, `meta.db.dat`, and `meta.db.dir`, but no mere `meta.db` in my "root" MultiMC folder.
Additionally, I do get a list for premade modpacks (which I assume reads from manifest.json), but any mods added with OMM does not persist.

(Also to clarify: `ui-v2` does not start, but my Python install is a snarl, so I'll get back to you on that one.)

**Comment by notjuliee** [comment]
Right, windows splits it up for some reason. Delete all 3 and try ui-v2 again?

What what?!?!?!? They both use the exact same persistence code, it makes absolutely 0 sense why one wouldn't work...

**Comment by Maddremor** [comment]
`ui-v2` does not start at all, and thus not related to this issue. Sorry if I'm being confusing. I'll start a separate issue for `ui-v2` if fixes are pushed into it.

**Comment by notjuliee** [comment]
I don't have the time to patch 1.1, and I've already made a ton of changes to meta handling in 2.0. So it would be great if you could get that working.

**Comment by Maddremor** [comment]
Got OMMv2 to run, still no persistance. A `meta.db.dat` and `meta.db.dir` are created, and seems to have mod data, but the list in OMMv2 is still empty.

**Comment by notjuliee** [comment]
Wtf.

I'm gonna rework persistence some more, I'll let you know when its read for another test.

**Comment by Maddremor** [comment]
Consider storing the mod list on a per instance basis for portability?

**Comment by notjuliee** [comment]
Yes, that's exactly what I'm working on.
