### ISSUE TITLE
[UI][ui-v2]Buttons next to mods/modpacks/instances lack icons.

### ISSUE THREAD

**Issue by Maddremor** [joonatoona/OpenMineMods#24]
The buttons next to listed items (ie. mods, modpacks, and instances) lack an icon, having `...` instead.

![image](https://user-images.githubusercontent.com/17386279/30533825-a1133fb2-9c5b-11e7-883b-1a8695ff2608.png)

Icons not implemented in OMMv2 yet, or buttons being too small to render the icons?

**Comment by notjuliee** [comment]
Ah crap.

To maintain a consistent look on Linux distros, I'm using system icons. I guess windows doesn't have them? I will have to do further testing.

**Comment by notjuliee** [comment]
Ok, I pushed a commit that should use bundled icons instead.

Can you try rebuilding the UI and running it again?

**Comment by Maddremor** [comment]
Icons look fine now.
