### ISSUE TITLE
[ui-v2]List of mods stuck on loading

### ISSUE THREAD

**Issue by Maddremor** [joonatoona/OpenMineMods#25]
List of remote mods does not finish loading (see image below).

Windows 10 x64
`ui-v2` branch
Fresh MultiMC instance and OMMv2 clone
![image](https://user-images.githubusercontent.com/17386279/30543842-cb504c42-9c84-11e7-8154-360b6d16187b.png)

**Comment by notjuliee** [comment]
Can you please pull and try again, and send the logs?

**Comment by Maddremor** [comment]
I might be a bit daft, but where would said log be generated, and in what format?

**Comment by notjuliee** [comment]
`stdout`, plain text.

It's the console output of the program. I'm still working on automatic log uploads.

**Comment by Maddremor** [comment]
Nope, no console output as far as I can see.
```
D:\Program Files (x86)\Minecraft\CustomSoftware\OpenMineMods>python OpenMineMods.py
[09/18/17 17:44:59][INFO] Starting OpenMineMods v1.1.0
[09/18/17 17:44:59][INFO] Data dir: F:/AppData/Roaming/python
['OpenMineMods.py']
```
Since it emerged after the icon fix, could it be related to the UI as opposed to networking?

**Comment by Maddremor** [comment]
The download buttons on on modpacks does nothing when pressed. The links to the Curse page of the modpack still works.

**Comment by notjuliee** [comment]
I'll look into that too, but I refer to the second badge in the README

Jeez man, gimme some time to implement everything :P

Modpack installation isn't implemented into the UI yet, would you like to help do that? :)

**Comment by Maddremor** [comment]
I'm not trying to stress you out, I promise. Good faith QA etc.
I would love to contribute, but my programming knowledge is essentially Python 101.

**Comment by notjuliee** [comment]
I know, free QA is always nice :)  
It's a good language to learn, it's pretty simple :D, just take a look at some of this projects code if you have the time.

**Comment by Maddremor** [comment]
Works as of latest version.
