### ISSUE TITLE
[ui-v2] No search function for mods

### ISSUE THREAD

**Issue by Maddremor** [joonatoona/OpenMineMods#26]
I can't remember if it's broken or not implemented yet, but while the list of most popular/downloaded/whatever is shown, the search function for mods does nothing.

Running `ui-v2` branch on last commit 2b3557e on Windows 10.

**Comment by notjuliee** [comment]
Yep, I can confirm that is unimplemented as of now.

I've been working on migrating to a local database, so expect mod search to be done pretty soon. This gives all kinds of fancy new features like realtime searching :D
