### ISSUE TITLE
does not save my multi mc install location

### ISSUE THREAD

**Issue by xlis1** [joonatoona/OpenMineMods#3]
This is a minor annoyance but whenever i open the down loader it asks for my MMC install again.

**Comment by notjuliee** [comment]
Ok, I belive I have identified and fixed the issue.

Go to `C:\Program Files (x86)\OpenMineMods\pkgs`, and replace `CurseAPI.py` and `GUI.py` with these ones:

https://raw.githubusercontent.com/joonatoona/OpenMineMods/master/CurseAPI.py

https://raw.githubusercontent.com/joonatoona/OpenMineMods/master/GUI.py
