### ISSUE TITLE
[Suggestion] Refresh instances button

### ISSUE THREAD

**Issue by Maddremor** [joonatoona/OpenMineMods#32]
If I want to create a new custom instance and absent-mindedly open OMM before I create a new instance in MultiMC, OMM has to be restarted for the instance to be listed.
I suggest adding a refresh button to the instance listing.

**Comment by notjuliee** [comment]
That was there eariler, but I got rid of it because it looked ugly. Any suggestions as to where the button should go?

**Comment by Maddremor** [comment]
Have a space below the instance list and place it there, although a single button doesn't warrant it. 
Inside the list itself as the lowest entry (might look weird).
Shunt it off to the settings menu.

I'm really not a UI person though.

**Comment by notjuliee** [comment]
I think shoving it to the settings menu might be the best idea, I'll do that.
