### ISSUE TITLE
Does not show all mods and downloads wrong version

### ISSUE THREAD

**Issue by ghost** [joonatoona/OpenMineMods#34]
Version 2.0.0 with MC 1.12.2 & MultiMC 0.5.0-945

This happen with more mods, but as an example I use JEI.
1) JEI is installed in the mods folder, but OMM does not see it.
2) When I download JEI with OMM, it downloads an older version (4.7.11.102 instead of 4.8.0.105)

**Comment by notjuliee** [comment]
Did you click the scan mods button in the instance info tab?

Don't know why it would be downloading an older version. I'll look into that.

**Comment by ghost** [comment]
Yes, I did a scan :)
Thnx
