### ISSUE TITLE
Cant find modpack

### ISSUE THREAD

**Issue by FliegendeWurst** [joonatoona/OpenMineMods#35]
I cant find [Modern Skyblock 2](https://minecraft.curseforge.com/projects/modern-skyblock-2) :(

**Comment by notjuliee** [comment]
Just tried it and it seemd to work just fine?

![2017-10-09_10 06 40](https://user-images.githubusercontent.com/5176397/31349810-a1d689de-acd9-11e7-9c45-b7bccadc055f.png)

Try forcing a cache update by deleting %appcache%/openminemods

**Comment by FliegendeWurst** [comment]
That worked, thanks 👍
