### ISSUE TITLE
Crash when attempting to install mod pack with colon in name on Win32

### ISSUE THREAD

**Issue by Aedda** [joonatoona/OpenMineMods#36]
On Win32 invalid path characters are \ / : * ? " < > |
----------
STACKTRACE
----------
NotADirectoryError: [WinError 267] The directory name is invalid: 'I:/SSDMC/MultiMC/instances/_MMC_TEMP/Project Ultimate: Reloaded'

  File "Utils\Downloader.py", line 30, in download_pack

**Comment by notjuliee** [comment]
Well crap. I assume it would just be best to strip out all those characters?

**Comment by Aedda** [comment]
That would probably be the best course. I installed the pack with Twitch and it stripped it out when installing.
