### ISSUE TITLE
Mods show up twice in modlist after installing new mods. Return to singularity when updating the mod

### ISSUE THREAD

**Issue by WeaselOnaStick** [joonatoona/OpenMineMods#42]
![image](https://user-images.githubusercontent.com/10953814/31575989-69b48b90-b11c-11e7-91ec-ddc59bc1200f.png)

And no, rescaning instance does not help.
Neither does restarting the application

**Comment by notjuliee** [comment]
I already fixed this issue in 2.1.5.

Please make sure you're on the latest version, delete `omm_dat.json` from your instance folder, then rescan the instance.
