### ISSUE TITLE
Release file insvisible

### ISSUE THREAD

**Issue by tlitookilakin** [joonatoona/OpenMineMods#43]
The latest release zip for windows is slightly broken. opening the zip normally shows an empty folder. the exe only showed up when I opened the zip with winrar. Just thought I'd let you know. (additionally, I have hidden files + folder set to visible in my system settings, so it's not that.)

**Comment by notjuliee** [comment]
I am unable to reproduce this issue on my Windows 7 build machine. What windows version are you using?

**Comment by tlitookilakin** [comment]
windows 8.1 (I know, I hate it, but I'm sort of stuck with it.)

**Comment by notjuliee** [comment]
I'll see if I can find an ISO to reproduce the issue.

**Comment by tlitookilakin** [comment]
it might be the file name. in winrar it shows up as ..\openminemods.exe
the prefix might be messing with windows.

**Comment by notjuliee** [comment]
...oh my god I'm an idiot. Lemme fix that right away.

**Comment by tlitookilakin** [comment]
lol

**Comment by notjuliee** [comment]
I update the file in the release, try [this one](https://github.com/OpenMineMods/OpenMineMods/releases/download/v2.1.5/Windows.zip)?

**Comment by tlitookilakin** [comment]
yep, that works fine!
