### ISSUE TITLE
Modpacks not showing up in browser?

### ISSUE THREAD

**Issue by WeaselOnaStick** [joonatoona/OpenMineMods#46]
https://mods.curse.com/modpacks/minecraft/274129-atm-3-lite
Cannot find this particular modpack but there may be others

**Comment by notjuliee** [comment]
I was unable to reproduce the issue (ignore the UI, the code is still identical)

![2017-10-18_11 35 52](https://user-images.githubusercontent.com/5176397/31736080-8c65fbf4-b3f8-11e7-933f-57dabe7bdd90.png)

Try clearing the cache? Just delete `%LocalAppData%\cache\openminemods`

**Comment by WeaselOnaStick** [comment]
deleting cache worked
