### ISSUE TITLE
In case you were wondering, the AUR package is no longer outdated

### ISSUE THREAD

**Issue by Zekromaster** [joonatoona/OpenMineMods#48]
I apologize for the inconvenience cause by sudden facts in my life that made me have to drastically reduce the time spent on mantaining stuff and general online life. These problems are now solved, so I hope I can get your trust back by mantaining the AUR package again, this time with no sudden disappearences.

I'm looking forwards to more updates. Keep up the great work!

(Also, this means you'll have to update the Readme next release)

**Comment by notjuliee** [comment]
Thank you! README has been updated.
