### ISSUE TITLE
Crash on removing mod with already removed file.

### ISSUE THREAD

**Issue by Maddremor** [joonatoona/OpenMineMods#5]
```
Traceback (most recent call last):
  File ".\GUI.py", line 141, in delete_clicked
    self.instance.uninstall_mod(mod)
  File "D:\Program Files (x86)\Minecraft\CustomSoftware\OpenMineMods\MultiMC.py", line 124, in uninstall_mod
    remove("{}/minecraft/mods/{}".format(self.path, filename))
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'D:\\Program Files (x86)\\Minecraft\\CustomSoftware\\MultiMC\\instances\\TestOne/minecraft/mods/ResourceLoader-MC1.12-1.5.2.jar'
```
Bug: 
Upon trying to remove a mod whose .jar file is no longer present in the instance, the software crashes. This was only tested by me on Windows launching GUI.py via cmd.

How to replicate:
Start the GUI version of the software.
Edit a modpack/instance.
Add a single mod twice.
Press remove on one of the duplicate mods.
Press remove on the remaining mod.
The program should now crash.

**Comment by notjuliee** [comment]
Ok, so as a temporary solution I added a check for the file existing.

I'll add checks so you can't install the same mod twice, because that's an issue too.

**Comment by Maddremor** [comment]
That fixed it.
