### ISSUE TITLE
Application does not launch.

### ISSUE THREAD

**Issue by Kaeks** [joonatoona/OpenMineMods#8]
As the title says, the app does not launch.
I'm starting it through the Windows Start Menu.

Further Information if needed:
Windows 10 64-Bit
AMD FX-6200 Processor
8GB RAM

**Comment by notjuliee** [comment]
Can you run `C:\Program Files (x86)\OpenMineMods\Python\python.exe C:\Program Files (x86)\OpenMineMods\OpenMineMods.launch.pyw` in a CMD window and paste the output here?

**Comment by Kaeks** [comment]
Not sure if I've done this right. I ran `start D:\ProgramFiles\OpenMineMods\Python\python.exe D:\ProgramFiles\OpenMineMods\OpenMineMods.launch.pyw` through CMD, a python window pops up for a split second then disappears without a message.
~~Perhaps installing the program on my 2nd HDD is the source of the problem?~~

Edit: Uninstalling and reinstalling into `C:\Program Files (x86)` has the same outcome.

**Comment by notjuliee** [comment]
Yeah, its not an issue with the install.

That should absolutely not open a Python window. Try just the first part of the command?

**Comment by Kaeks** [comment]
Running `start "C:\Program Files (x86)\OpenMineMods\OpenMineMods.launch.pyw"` opens up a normal Windows command prompt, though with the title being the path.

**Comment by Kaeks** [comment]
Running `start "C:\Program Files (x86)\OpenMineMods\Python\python.exe"` opens up another Windows command prompt, though with the title being the path

**Comment by notjuliee** [comment]
Wat?!? That shouldn't even be possible. Try without `start`?

**Comment by Kaeks** [comment]
Ah, there we go. Trying without `start` shows this in the cmd:
`Python 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:14:34) [MSC v.1900 32 bit (Intel)] on win32`

Also, using the full command shows an error:
C:\Users\Kaeks>"C:\Program Files (x86)\OpenMineMods\Python\python.exe" "C:\Program Files (x86)\OpenMineMods\OpenMineMods.launch.pyw"`
Traceback (most recent call last):
  File "shelve.py", line 111, in __getitem__
KeyError: 'baseDir'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\OpenMineMods\OpenMineMods.launch.pyw", line 30, in <module>
    from GUI import main
  File "C:\Program Files (x86)\OpenMineMods\pkgs\GUI.py", line 127, in <module>
    main()
  File "C:\Program Files (x86)\OpenMineMods\pkgs\GUI.py", line 124, in main
    win2 = AppWindow()
  File "C:\Program Files (x86)\OpenMineMods\pkgs\GUI.py", line 17, in __init__
    self.curse = CurseAPI()
  File "C:\Program Files (x86)\OpenMineMods\pkgs\CurseAPI.py", line 46, in __init__
    self.baseDir = self.db["baseDir"]
  File "shelve.py", line 114, in __getitem__
_pickle.UnpicklingError: pickle data was truncated

**Comment by notjuliee** [comment]
Is there a file in your home directory named `omm.db.<whatever>`?

**Comment by Kaeks** [comment]
There are omm.db.bak, omm.db.dat and omm.db.dir

.dir and .bak contain the following:
'packs', (0, 6)
'baseDir', (512, 10)

**Comment by notjuliee** [comment]
Can you delete all three, then try running the full command again?

It should ask for your MultiMC install folder.

**Comment by Kaeks** [comment]
That seems to have fixed it! Thanks!

**Comment by notjuliee** [comment]
Awesome! I'll add error handling for that.

Now the app menu shortcut should work too :D
